// Import UI component styles that are used in templates
import '../../ui/src/Text/index.scss';
import '../../ui/src/Card/index.scss';
import '../../ui/src/Grid/index.scss';
import '../../ui/src/Flex/index.scss';
import '../../ui/src/Section/index.scss';
import '../../ui/src/Container/index.scss';
import '../../ui/src/Title/index.scss';
import '../../ui/src/Button/index.scss';
// Import template component styles
import './components/CallToAction/index.scss';
import './components/ComicPanels/index.scss';
import './components/ContentSection/index.scss';
import './components/DataStream/index.scss';
import './components/Footer/index.scss';
import './components/Header/index.scss';
import './components/Hero/index.scss';
import './components/ImageGrid/index.scss';
import './components/ItemCard/index.scss';
import './components/ItemGrid/index.scss';
import './components/Marquee/index.scss';
import './components/QuoteBlock/index.scss';
import './components/SpeechBubbleTestimonials/index.scss';
import './components/SplitScreen/index.scss';
import './components/StatsCounter/index.scss';
import './components/TechSpecs/index.scss';
import './components/Terminal/index.scss';
import './components/TestimonialCards/index.scss';
import './components/Timeline/index.scss';
